PDF_FOLDER = "C:/Users/user/Desktop/fek"
CHUNK_SIZE = 500
CHUNK_OVERLAP = 50
MINILM_MODEL = "sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2"
DEFAULT_MODEL = "krikri"
LLM_MODELS= {"krikri": "ilsp/Llama-Krikri-8B-Instruct", "tinyllama": "TinyLlama/TinyLlama-1.1B-Chat-v1.0"}
TOP_K = 2
BGE_MODEL = "BAAI/bge-m3"
MINILM_WEIGHT = 0.5
BGE_WEIGHT = 0.5